# @package _global_

defaults:
  - pointnav_base
  - /habitat/dataset/pointnav: gibson
  - _self_

habitat:
  environment:
    max_episode_steps: 1000
  simulator:
    turn_angle: 30
    forward_step_size: 0.25
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 256
            height: 256
            hfov: 90
          depth_sensor:
            width: 256
            height: 256
            hfov: 90
  dataset:
    scenes_dir: "/cluster/work/rsl/lmilikic/gibson"