# @package habitat.dataset

defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: ImageNav-v1
split: train
# data_path: data/datasets/imagenav/hm3d/v1/{split}/{split}.json.gz
data_path: data/datasets/instance_imagenav/hm3d/v2/{split}/{split}.json.gz
