defaults:
  - task_config_base
  - actions:
      - stop
      - move_forward
      - turn_left
      - turn_right
  - measurements:
      - distance_to_goal
      - success
      - spl
      - distance_to_goal_reward
  - lab_sensors:
      - imagegoal_sensor
      - compass_sensor
      - gps_sensor
  - _self_

type: Nav-v0
end_on_success: True
reward_measure: "distance_to_goal_reward"
success_measure: "spl"
measurements:
  success:
    success_distance: 2.5
    success_ratio: 0.4


#   distance_to_goal:
#     distance_to: VIEW_POINTS
