defaults:
  - task_config_base
  - actions:
    - stop
    - move_forward
    - turn_left
    - turn_right
  - measurements:
    - distance_to_goal
    - success
    - spl
    - distance_to_goal_reward
    - num_steps
  - lab_sensors:
    - pointgoal_with_gps_compass_sensor
    - compass_sensor
    - gps_sensor
  - _self_

type: Nav-v0
end_on_success: True
reward_measure: "distance_to_goal_reward"
success_measure: "spl"
goal_sensor_uuid: pointgoal_with_gps_compass
measurements:
  success:
    success_distance: 1.
lab_sensors:
  pointgoal_with_gps_compass_sensor:
    distance_norm: 6.5
    # noise
    noise_enabled: True
    noise_sigma: 0.55
    noise_alpha: 0.99
    noise_spike_prob: 0.10
    noise_spike_scale: 2.5
    # conf
    return_confidence: True
    confidence_coef: 0.25
    confidence_sigma: 0.25
    confidence_alpha: 0.50
