# @package habitat.dataset

defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: InstanceImageNav-v1 # PointNav-v1
split: val
data_path: data/datasets/pointnav/hm3d/v2/{split}/{split}.json.gz
