# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: instance_imagenav # pointnav
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: rgbd_agent
  - /habitat/dataset/instance_imagenav: hm3d_v2
  - _self_

habitat:
  environment:
    max_episode_steps: 1000
  simulator:
    turn_angle: 15
    scene_dataset: "/cluster/work/rsl/lmilikic/hm3d/hm3d_annotated_basis.scene_dataset_config.json"
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 256
            height: 256
            hfov: 90
            position: [0, 0.9, 0]
          depth_sensor:
            width: 256
            height: 256
            hfov: 90
            min_depth: 0.5
            max_depth: 5.0
            position: [0, 0.9, 0]
        height: 1.41
        radius: 0.17
    habitat_sim_v0:
      # gpu_device_id: 0
      allow_sliding: True
  dataset:
    scenes_dir: "/cluster/work/rsl/lmilikic/hm3d"

# hm3d_semantic_v0.2