# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: instance_imagenav
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: rgbd_agent
  - /habitat/dataset/instance_imagenav: hm3d_v1
  - _self_

habitat:
  environment:
    max_episode_steps: 1000
  simulator:
    turn_angle: 30
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
            hfov: 79
          depth_sensor:
            width: 256
            height: 256
            hfov: 90
            min_depth: 0.0
            max_depth: 100.0
            normalize_depth: False
    habitat_sim_v0:
      allow_sliding: True
